### ISSUE TITLE
Change the keyboard shortcut for registered users

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#1879] opened 2016-02-18 09:41 UTC
Hi,
On Linux (I don't know about others), Ctrl+Shift+U is the shortcut for Unicode, therefore please change the menu shortcut for registered users.

**Comment by un1versal** [comment] 2016-02-18 09:43
Are you talking about the OS shortcut vs application shortcut? If so they are unrelated even on Linux.

**Comment by kartagis** [comment] 2016-02-18 09:44
I'm talking about application shortcut (note the Registered Users part)

**Comment by un1versal** [comment] 2016-02-18 09:47
Again, the application shortcut (for reg users) works independently from the Operative System shortcut for Unicode, at least it does here. So Im asking what youre talking about as I dont see an issue personally.

You need to select KVIrc app in order for the shortcut to work in KVIrc. in the OS idk, Im currently trying to trigger anything in OS via this same shortcut and cannot.

**Comment by un1versal** [comment] 2016-02-18 09:52
Sorry, can you please specify what the issue is and explain how to duplicate, I cant see any problem.

**Comment by kartagis** [comment] 2016-02-18 09:54
If you press Ctrl+Shift+U to input unicode, Registered Users dialog will open.

**Comment by un1versal** [comment] 2016-02-18 09:55
WHERE?

**Comment by kartagis** [comment] 2016-02-18 09:55
in KvIRC

**Comment by un1versal** [comment] 2016-02-18 09:58
sigh...

**Comment by kartagis** [comment] 2016-02-18 09:58
Well, what exactly are you asking?

**Comment by staticfox** [comment] 2016-02-18 09:59
Distro? Running 15.04 on my laptop and can't reproduce.

**Comment by kartagis** [comment] 2016-02-18 09:59
@staticfox ubuntu 14.04

**Comment by staticfox** [comment] 2016-02-18 10:01
DE/WM? Guessing unity?

**Comment by kartagis** [comment] 2016-02-18 10:01
@staticfox cinnamon

**Comment by un1versal** [comment] 2016-02-18 10:02
Cant see any interference with the OS...

**Comment by un1versal** [comment] 2016-02-18 10:08
FYI the resposible bit of code is https://github.com/kvirc/KVIrc/blob/bb62eb90a2f4774b15741e7365fef568f241d7ed/src/kvilib/config/kvi_shortcuts.h#L164

In principle assuming there is an issue, the problem is replacing that key combo for something that makes sense and isnt already in use.
Suggestions welcome.

ATM Im struggling to see any issue caused here by this as is.

**Comment by un1versal** [comment] 2016-02-18 10:12
@kartagis can you please make a video of the issue?

**Comment by DarthGandalf** [comment] 2016-02-18 10:41
"press Ctrl+Shift+U to input unicode" - this is shortcut of what? What do
you mean by "input unicode"?

2016-02-18 10:12 GMT+00:00 un1versal notifications@github.com:

**Comment by kartagis** [comment] 2016-02-18 10:48
@un1versal @staticfox @DarthGandalf please see https://dl.dropboxusercontent.com/u/11918318/kvirc.mp4

**Comment by un1versal** [comment] 2016-02-18 10:50
that video doesnt work

**Comment by kartagis** [comment] 2016-02-18 10:51
What do you mean it doesn't work?

**Comment by Heufneutje** [comment] 2016-02-18 10:55
Doesn't seem to play in browser. It works fine if you download the video though.

**Comment by kartagis** [comment] 2016-02-18 11:01
It plays in my browser

**Comment by un1versal** [comment] 2016-02-18 11:01
> Doesn't seem to play in browser. It works fine if you download the video though.

exactly

> It plays in my browser

Doesnt play in mine

**Comment by DarthGandalf** [comment] 2016-02-18 11:02
I didn't know about such way to type unicode, but it works for me in kvirc
too.

2016-02-18 11:01 GMT+00:00 kartagis notifications@github.com:

**Comment by DarthGandalf** [comment] 2016-02-18 11:02
It depends on browser, I guess. Anyway, this issue is not about browser,
but about typing unicode

2016-02-18 11:01 GMT+00:00 un1versal notifications@github.com:

**Comment by DarthGandalf** [comment] 2016-02-18 11:07
Oh, the dialog doesn't open though. I see the issue now.

**Comment by un1versal** [comment] 2016-02-18 13:45
The dialog opens just fine.

**Comment by un1versal** [comment] 2016-02-18 15:45
Closing this, there is no issue. the registered users dialog shortcut has nothing to do with the ability to enter Unicode into kvirc input line without having to press ctrl+shift+u, you dont need to press ctrl+shift+u to enter unicode into kvirc.
If you press ctrl+shift+u the registered users dialog opens as expected.

If there is any issue please explain in detailed step how to reproduce, then we can reopen this and relabel

The only issue is in (some) Linux distros some Unicode characters show up as a rectangle instead of rendering to the right character for instance alt+1 alt+2 etc... clearly the fonts support it if you generate the characters elsewhere and paste them they show up.
My guess is that that latter issue is caused by our lovely custom input box + Linux, since this wont happen in OSX or windows apparently.

**Comment by wodim** [comment] 2016-02-18 16:03
Once again, and correct me if I'm wrong, that way of inputting unicode characters is only available in GTK applications.

**Comment by wodim** [comment] 2016-02-18 16:18
Ah well, maybe this is possible with a custom IM method, or at least that's what it looks like according to the video. So it's a matter of changing the shortcut I guess.

**Comment by DarthGandalf** [comment] 2016-02-18 16:48
@un1versal I've already confirmed there is an issue...
@wodim works for me in KVIrc (at least with Qt4, will try with Qt5).

2016-02-18 16:18 GMT+00:00 wodim notifications@github.com:

**Comment by un1versal** [comment] 2016-05-23 14:47
Its weird, in Qt 5.2.1 (linux) this works press ctrl+shift+u and up the reg users comes up with Qt 5.5.1 seems like its now not working anymore.

**Comment by un1versal** [comment] 2016-05-24 15:29
Nope, nothing related to Qt...

It actually depends where you set your focus, for instance, in input line you can duplicate the issue described here, it will not open the reg users dialog.
However click just above in IRC view prior to pressing key sequence, it will open the reg user dialog without fail.

so idk, Im back to asking wheres the issue exactly again?

**Closed as completed** 2016-06-10 21:32 UTC
Labels: Type ■ Bug, Type ■ Feature Request, Status ■ Confirmed
