### ISSUE TITLE
Auto rejoin channels does not store channel keys (+k)

### ISSUE THREAD

**Issue by VFiber** [kvirc/KVIrc#1873] opened 2016-02-09 09:45 UTC
It might be two separate issue or one alone:

If I join a channel locked with a key and add that channel into auto-join, it does not add the key into auto-join. 
Gives a "cannot join due to lack of correct key" on startup and does not join to the keyed channel.

If I add the chan manually (with the key) it forgets between reconnects (does not save correctly?), and does not join either.

Windows 7x64, 10x64 KVIrc Aria 4.9.1, revision: git-6221-gc95fb88, sources date: 20160102, built on: 2016-02-08 02:09:09 UTC

**Comment by SoniEx2** [comment] 2016-02-09 12:14
Sounds like channels don't store keys, and so autojoin doesn't pick up on that. If you join any channel, without adding it to autojoin, and cause a reconnect, does it still rejoin? If so that rejoining part isn't related to autojoin. (I don't use KVIrc so I don't know :P)

**Comment by un1versal** [comment] 2016-02-09 17:28
> (I don't use KVIrc so I don't know :P)

Thats a joke, right? Why even bother to make feature requests for something you dont use? :confused:

**Comment by SoniEx2** [comment] 2016-02-09 20:38
@un1versal Talk to me on IRC about it. I may not use KVIrc myself but I interact with many KVIrc users.

**Comment by un1versal** [comment] 2016-02-09 20:53
So let them speak for themselves perhaps?

**Comment by VFiber** [comment] 2016-02-09 22:34
Okay, whats weird it works now: it joins without a problem. 
My guess is: within session, some setting-save-load doesn't happen, but on quit it saves and during next startup it loads these settings correctly.

**Comment by un1versal** [comment] 2016-02-10 00:25
@VFiber theres quite a lot of issues with settings saving and a bug report for it. It makes me wonder if its related to the many **coverity** memory corruption that havent been fixed.

**Comment by un1versal** [comment] 2016-07-05 02:54
This is essentially a duplicate of https://github.com/kvirc/KVIrc/issues/416

So Ill merge there and close here.

**Closed as completed by un1versal** 2016-07-05 02:54 UTC
Labels: Status  ■ Duplicate, Type ■ Bug, Status ■ Confirmed
