### ISSUE TITLE
option to ban bad nick colors

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1054] opened 2015-07-26 03:09 UTC
**Reported by TheRipper on 22 Dec 2010 16:08:00 UTC**
Nick colors are nice but they have one main problem: bad combinations that are unreadable or simply ugly.

In the text options menu, there should be a button that opens a dialog which allows the user to uncheck bad combinations. a simple 2 dimensional array with 16 bools per dimension should be able to store that data.

I will add a (rough) example of how I imagine the dialog could work.

It's basically a table of foreground and background colors with example (a) and a checkbox. the outer checkboxes check/uncheck all colors in their row/column.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1054

**Comment by un1versal** [comment] 2015-11-03 12:07
This is essentially a duplicate of https://github.com/kvirc/KVIrc/issues/353 merging with that one and closing here

**Closed as completed by un1versal** 2015-11-03 12:07 UTC
Labels: Component ■ Core, Status  ■ Duplicate, Type ■ Feature Request
