### ISSUE TITLE
Remove Qt 4 support

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1650] opened 2015-10-02 18:09 UTC
What is stopping us from doing this? Maybe supporting people who still do not have Qt 5 on Linux? Do those still exist?

I'm asking because of changes such as df6c711 or ed9d80e.

**Comment by DarthGandalf** [comment] 2015-10-02 20:07
Yes, they exist.
E.g. ubuntu 12.04 lts.

**Comment by DarthGandalf** [comment] 2015-10-02 20:08
for ubuntu, ppa can probably be used though.

**Comment by wodim** [comment] 2015-10-02 20:22
@DarthGandalf In that case we have to bundle Qt 5 in our PPA or...? There is no Qt 5 at all for 12.04?

**Comment by DarthGandalf** [comment] 2015-10-02 21:42
Either https://launchpad.net/~ubuntu-sdk-team or https://launchpad.net/~beineri should work... (from http://askubuntu.com/questions/279421/how-can-i-install-qt-5-x-on-12-04-lts)
Well, travis has 12.04, you can try to use qt5 from one of those ppas.

**Comment by wodim** [comment] 2015-10-02 22:22
I could understand if we needed to support Qt 4 for for example one more year, but I just checked and 12.04 will continue to have support until almost 2018. So maybe a PPA is a reasonable solution.

**Comment by ctrlaltca** [comment] 2015-10-03 07:12
Things that i found to be problematic in dropping qt4, and sticking with qt5 only:
- since qt 5.3.0, they dropped support for processors without sse2 instruction set (pentium < 4 and AMD Athlon)
- osx < 10.7 is no more supported (so no more carbon, only cocoa)
- windows xp is still "supported", but not even tested anymore, so expect some breakage on new versions.

More info here: http://doc.qt.io/QtSupportedPlatforms/index.html

**Comment by DarthGandalf** [comment] 2015-10-16 23:18
Travis can use 14.04 now, http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
14.04 has qt 5.2

**Comment by un1versal** [comment] 2015-10-22 08:10
32-bit builds wont run with Qt5 (on some machines) Some complaint in IRC

So I think for now we should provide at least random git builds with Qt4 for the die hard, cant afford newer machine, I want my windows 4.1 to work kind of guys.

**Comment by Dessa** [comment] 2015-10-22 08:48
so has it been confirmed that qt4 builds work or is that some random guess based on that older builds worked? because that has little relevance, due to code changes.

i'd rather get this done sooner then later so i'll try to get a debug build of qt5 and friends done over the weekend, maybe a kvirc debug build would be sufficient but who knows.

**Comment by un1versal** [comment] 2015-10-22 09:28
> ctrlaltca wrote:
> since qt 5.3.0, they dropped support for processors without sse2 instruction set (pentium < 4 and AMD Athlon)

@Dessa 
And Leopoldf (I imagine hes not the only one) is using some ancinet hw in some windows 32-bit so I imagine thats why.

I dont care either way beyond testing the theory, imo plenty 64bit machines are cheap as chips these days.

**Comment by DarthGandalf** [comment] 2016-01-31 20:42
As @Dessa pointed out, Qt4 isn't supported anymore since Dec 2015.
http://doc.qt.io/QtSupportedPlatforms/index.html

**Comment by un1versal** [comment] 2016-07-07 21:01
Qt4 isnt supported anymore, been ripped from cmake on https://github.com/kvirc/KVIrc/pull/1859 and all the ifdefs are gone also so anything that builds with qt4 is now irrelevant,

If theres anything else cleanup wise in code feel free to reopen this ticket and provide details

Closing as fixed

**Closed as completed by un1versal** 2016-07-07 21:01 UTC
Labels: Component ■ Core, Status ■ Fixed
