### ISSUE TITLE
Broken links on website kvirc dot net

### ISSUE THREAD

**Issue by knakamura8** [kvirc/KVIrc#2524] opened 2022-05-22 04:29 UTC
Under kvirc.net, "KVIrc related" on the top right bar, when clicking on Official forum and Russian site link to a dead page and a seemingly unrelated website.

**Comment by abazaba855** [comment] 2023-12-24 17:58
The entire www.kvirc.net website seems to be completely abandoned for a long time now, I wonder if the current maintainers even have control over the website anymore. The SSL/TLS connection is of such a nature that Chrome and Firefox even ask me what certificate *I* want to send to their site when connecting, a lot of the links to downloads (themes, 'official downloads') are through ftp even though browsers stopped supporting that a long time ago, the 'www mirror' of www.kvirc.de isnt even registered in DNS anymore, the mailing list related links point to lists.omnikron.net that isnt registered in DNS anymore either, etc.

**Comment by ctrlaltca** [comment] 2023-12-24 21:13
Yep, we know. The website is under @pragmaware 's control, it used to auto-update from https://github.com/kvirc/kvirc-www , but that automation stopped working dsome time ago.
The situation is unfortunate and i hope it will be fixed in the future, but we can't do nothing right now.

I'm not sure about the SSL problem you are reporting, it's a common [Let's Encrypt](https://letsencrypt.org/) certificate, it seems to work normally here.

**Comment by DarthGandalf** [comment] 2023-12-24 22:38
I also randomly cannot open it due to bad SSL cert. Today it doesn't work in Firefox, but works in Vivaldi.

**Comment by knakamura8** [comment] 2023-12-25 05:12
@ctrlaltca Hello!  Coming in after two of my tickets got necro'd!  Glad that the team is still around, as KVIrc is still, by far, the best IRC software out there.  I also noticed just now that the Forum links for example are still dead, etc.  Perhaps create a Wiki page here on GitHub where people can contribute current issues on the website in a collaborative manner, such that they may be fixed?

For example:

**Bugs:**

- [ ] http://www.kvirc.net/?id=status&lang=en references 4.2.0 Equilibrium, rather than 5.0.0 Aria
- [ ] http://www.kvirc.net/?id=download&lang=en references 4.2.0 Equilibrium, rather than 5.0.0 Aria
- [ ] http://www.kvirc.net/ Top right links to Official forum and Russian site are both dead

**Suggests:**

- [ ] Replace Official forum and Russian site links with archive links

**Comment by abazaba855** [comment] 2023-12-25 18:08
> Yep, we know. The website is under @pragmaware 's control, it used to auto-update from https://github.com/kvirc/kvirc-www , but that automation stopped working dsome time ago. The situation is unfortunate and i hope it will be fixed in the future, but we can't do nothing right now.
> 

That's unfortunate indeed. The only (but perhaps unfeasible and unrealistic) alternative I can come up with, is to register a new domain (www.kvirc.org perhaps ?), and then use that (and explain the situation there) and then hope/pray that the search engines start listing that higher in the search results than the old site.


> 
> I'm not sure about the SSL problem you are reporting, it's a common [Let's Encrypt](https://letsencrypt.org/) certificate, it seems to work normally here.

When I make the first connect with Chrome, it shows me this:
![select-certificate-chrome](https://github.com/kvirc/KVIrc/assets/106878151/e5bd79fc-61b0-4dae-857d-d092c4eab79c)

and Firefox this :

![select-certificate-firefox](https://github.com/kvirc/KVIrc/assets/106878151/37787d8e-f488-433a-86fc-5fee835819fe)

And Microsoft Edge this:

![select-certificate-msedge](https://github.com/kvirc/KVIrc/assets/106878151/a15872bd-fd48-4231-b9b7-2e3bb4265900)

but if I then proceed to click on 'cancel/don't send certificate', I still get access to the site. If it's not due to the certificate, it might be due to the specific (SSl/TLS ) configuration of the webserver that's serving up www.kvirc.net.

**Comment by ctrlaltca** [comment] 2023-12-25 21:06
@knakamura8 issues for the website should be reported on its own repo: https://github.com/kvirc/kvirc-www/issues
The repo already contains fixes for some of the issues. The website is supposed to update automatically from that repo, but this automation is not working currently.

@abazaba855 thank you for confirming the issue about the ssl certificate. I'm not sure about the cause, it could be a misconfigured server or some other issue, but having no control over the website we can't do anything right now.
Hopefully @pragmaware will notice this issue soon

**Comment by abazaba855** [comment] 2023-12-27 15:07
> @knakamura8 issues for the website should be reported on its own repo: https://github.com/kvirc/kvirc-www/issues The repo already contains fixes for some of the issues. The website is supposed to update automatically from that repo, but this automation is not working currently.
> 
@ctrlaltca
Done.
https://github.com/kvirc/kvirc-www/issues/29

**Comment by pragmaware** [comment] 2024-01-14 16:57
Sorry for lagging a little bit. I'll take a look at the website now. Need to move it to a different machine.

**Comment by pragmaware** [comment] 2024-01-14 18:11
- Site moved to a new server (allow some time for DNS to propagate).
- Installed a new SSL certificate - we should be OK for the next 5 years
- The site is now autoupdating from git every 10 minutes

**Comment by DarthGandalf** [comment] 2024-01-14 18:23
@pragmaware thanks, works for me now.

Can you give one of us access too, to be able to fix it when it breaks next time?

E.g. it will break on 12 Feb 2025, that's when the current certificate will end.

**Comment by pragmaware** [comment] 2024-01-14 20:58
So the machine is a production one that I monitor quite frequently (as opposed to the previous one).
We're no longer using let's encrypt for the certificate. It's a commercial certificate from Comodo tied to my e-mail. It's set to auto re-issue every year: I'll get an e-mail about it and will update.

**Comment by knakamura8** [comment] 2024-01-15 02:18
@pragmaware Thanks!  Saw your post in the other thread, as well!

**Comment by ctrlaltca** [comment] 2024-01-16 17:09
Fixed issues reported on this ticket, should be available shortly in the website.
Please open separate issues on the kvirc-www repo for new issues on the website: https://github.com/kvirc/kvirc-www/issues

**Closed as completed by ctrlaltca** 2024-01-16 17:09 UTC
