### ISSUE TITLE
Channel name completing doesn't exactly complete.

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#2126] opened 2016-08-31 06:58 UTC
### Expected behavior

I've got two channel names in the buffer starting with ##javascript. One is ##javascript and the other is ##javascript. (dot appended the channel name). Since these are practically the same, I'd expect KVIrc to complete until the dot  
### Actual behavior

Doesn't complete at all, prompting me to type the channel name in full.

![screenshot 2016-08-31 09 55 24](https://cloud.githubusercontent.com/assets/1607518/18119021/24517c46-6f61-11e6-83e7-6f36dc4b2a9e.png)
### Steps to reproduce the issue
1. Make sure you have similar channel names (like #KVIrc and #kvirc)
2. Try to complete by hitting Tab
3. Fail
### System information

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Mac OS X
System version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
Architecture: x86_64
Qt version: 5.6.1
Qt theme: macintosh

Build Info:
Build date: 2016-08-27 03:24:49 UTC
Sources date: 20160825
Revision number: git-6958-g901914e
System name: Darwin-15.6.0
CPU name: x86_64
Build command: /usr/local/Cellar/cmake/3.5.2/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/Users/Matt/Documents/projects/kvirc/KVIrc/build/KVIrc.app
   Threads=POSIX
Compiler name: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
Compiler flags: N/A
Qt version: 5.6.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS

```

```

**Comment by wodim** [comment] 2016-08-31 07:56
I can't really repro on Windows

**Comment by kartagis** [comment] 2016-08-31 07:58
Did you follow the same steps?

**Comment by staticfox** [comment] 2016-08-31 07:58
I can repro, windows here.

**Comment by un1versal** [comment] 2016-08-31 08:01
Duplicate of https://github.com/kvirc/KVIrc/issues/1009?

**Comment by wodim** [comment] 2016-08-31 08:14
no

**Comment by kartagis** [comment] 2016-08-31 08:15
I'd say no too

**Comment by un1versal** [comment] 2016-08-31 09:19
#1009 its about tab completion for channels (what this is) which in last post by ctrlaltca clearly states its not supported https://github.com/kvirc/KVIrc/issues/1009#issuecomment-124935201

**Comment by kartagis** [comment] 2016-08-31 09:22
I'd still say no, as older versions had this feature.

**Comment by wodim** [comment] 2016-08-31 09:22
I think you did not understand this ticket.

**Comment by un1versal** [comment] 2016-08-31 09:34
Well... #1009 works so that fine and closed.

For this ticket its weirder, theres way more going on., a few days ago while testing #2114 I added `#KVIrc!test` and am not joined to that channel anymore.
Now I added and joined `#kvarc` 
- testing this against `#kvarc` and `#kvirc` 

typed #k and tab

`[09:19:56] 4 matches: #KVIrc, #kodi-linux, #KVIrc!test, #kvarc`

Why is  `#KVIrc!test` in there? Im not joined to this channel... should it appear on this list?
-  testing this against `#kvarc`, `#KVIrc` and `#kvirc` 

Need to type `#kva` + tab to get a full completion (seems sort of normal at first look)

What is failing on completion is **Capital** letters `#KVI` + tab that doesnt complete any channel names that start or contain any capital letters

**Comment by un1versal** [comment] 2016-08-31 09:44
added channels with dot at end `#kvirc.`

completion of these channels only works when channel is joined and selected on windowlist

also note on tab completion for channels with Capital letters the same happens. 

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-36-generic
System version: #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-27 07:43:09 UTC
Sources date: 20160825
Revision number: git-6958-g901914e
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Closed as completed** 2016-08-31 15:46 UTC
Labels: Type ■ Bug, Status ■ Confirmed
