### ISSUE TITLE
Problem with KVirc's Window Stack

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1383] opened 2015-07-26 03:46 UTC
**Reported by sync on 30 Apr 2013 00:32:44 UTC**
This description will be pretty much the same as my e-mail to the mail list.
Following Szymon's request, I'll be opening this bug ticket.

Suppose you have 3 windows opened inside KVirc, the first one is the Console Window, second, my channel window and for last, some random query window.

Here's KVirc behavior:
If I close this query window, the next window to get focus will be the Console Window.

What KVirc behavior should be:
If I close the query window, KVirc should focus the previous active window in my list, like so:
Console -> #myChannel -> myQuery.
I close the Query Window.
Focus goes to #myChannel window.

Or if I have these stacked windows:
Console -> #chan1 -> #chan3 -> #chan2 ->query1 -> query2 -> dcc get.

I close my dcc get window and focus should go to the query2 window, same will happen if I close query2 window, focus goes to query1 window.

My window list now looks like this:
Console -> #chan1 -> chan3 -> #chan2

If I close my #chan2 window, focus goes to #chan3.

The same behavior should be observed if I have more than 1 Console window (multi-network) the focused window should be the nearest stacked window from the closed one.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1383

**Comment by DarthGandalf** [comment] 2015-07-26 03:46
**Modified by sync on 30 Apr 2013 00:40:55**
Summary: Problem with KVirc's Window Stac → Problem with KVirc's Window Stack

**Comment by un1versal** [comment] 2015-12-30 05:05
MDI windowing is no more also, wondering if SDI has cured it. I cant reproduce this

I think the undocking/docking behavior follows this bug report also... But thats something else.

Marking as fixed, since current build the focus behaves as user expectes

**Closed as completed by un1versal** 2015-12-30 05:05 UTC
Labels: Component ■ GUI, Status ■ Fixed, Type ■ Bug, Version ■ 4.2.0 Equilibrium
