### ISSUE TITLE
Channel name semi-highlighted after scrolling of list of channels

### ISSUE THREAD

**Issue by Arfrever** [kvirc/KVIrc#1897] opened 2016-03-03 16:47 UTC
If I press long "rectangle" used to scroll list of channels and move cursor up or down AND to the left so that it points to name of any channel and if I stop pressing mouse button in this moment, then name of that channel will become semi-highlighted.

(Semi-highlighting does not stop when moving cursor over name of that channel.)
# fcitx in below example:

![kvirc_channels](https://cloud.githubusercontent.com/assets/656294/13501569/8474c854-e167-11e5-88b6-573df79dd3b4.png)

```
Executable Information

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-02-25 03:59:53 UTC
Sources date: 20160102
Revision number: fb3d7d44b0a90afea71c1775d4511e3807ab2c63
System name: Linux
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -fno-ident -frecord-gcc-switches -pipe -Wall -fno-strict-aliasing 
Qt version: 5.5.1
```

**Comment by un1versal** [comment] 2016-03-03 17:21
I think this is a duplicate bug will need to verify later

**Comment by un1versal** [comment] 2016-03-09 12:53
Yes this is a duplicate of https://github.com/kvirc/KVIrc/issues/1301

Will merge this there.

(problem is with these merges is that devs like pragma may not look at older bug entries and this is closed and then the other bug forgotten)

**Closed as completed by un1versal** 2016-03-09 12:53 UTC
Labels: Status  ■ Duplicate, Type ■ Bug, Status ■ Confirmed
