### ISSUE TITLE
Implement color 99

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#1877] opened 2016-02-12 20:23 UTC
http://www.mirc.com/colors.html

> Additionally you can use color 99 to indicate a transparent color.

**Comment by un1versal** [comment] 2016-02-13 01:38
+1 This would be useful if that was implemented as a background color for the smart nicks feature it would solve the issue with that issue #353

On its own this has little value imo.

See you in 10 years. :grinning: Maybe by then you actually use KVIrc

**Comment by un1versal** [comment] 2016-08-17 09:55
This would be a really nice feature it would solve a few problems too if it were extended...

also it would solve the issue if a user wants to send a hidden transparent message. Using colors would stand out depending on themes used by others.

so this would need to be implemented and extended to several areas to kill many birds with one stone.

**Comment by IceN9ne** [comment] 2016-11-16 21:10
What's the point of having a transparent color code? I guess I'm not understanding what it's supposed to look like when used. Is this just `RGBA(255,255,255,0)`?

What does `\x0301,99X\x03`, `\x0399,01X\x03`, and `\x0399X\x03` look like when displayed in the client (if implemented)?

**Comment by SoniEx2** [comment] 2016-11-16 21:54
Most, if not all clients, implement foreground color 99 as the default text color, and background color 99 as either transparent or the default background color.

**Comment by IceN9ne** [comment] 2018-11-27 01:35
Duplicate of #1337.

**Closed as completed by IceN9ne** 2018-11-27 01:35 UTC
Labels: Type ■ Feature Request
