### ISSUE TITLE
Notify is not working + Notify List isnt populated

### ISSUE THREAD

**Issue by krambock** [kvirc/KVIrc#2003] opened 2016-06-07 15:03 UTC
### Expected behavior

When you have users on the notify list registered, as they come online they should appear on the notify window.
### Actual behavior

Notify is not working at all.  the users registered are not listed, not notified if they are online, went offline.. 
### Steps to reproduce the issue
1. Log into any IRC server (have tried several)
   2.Register some nick (have used different methods, quick, full , wizard) 
2. Open the Notify window.. no users listed (except for own)
### System information

`KVIrc 4.9.2 'Aria'

Información en tiempo de ejecución:
System name: Windows Release : 6.1.7601
System version: Windows 7 Professional (x64) Service Pack 1 (Build 7601)
Arquitectura: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.5.1
Qt theme: windowsvista

Información de compilación:
Build date: 2016-06-07 07:57:55 UTC
Sources date: 20160607
Revision number: git-6700-g03cee1d
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS`

Windows 7 Professional Edition, 64 bits`

```
[//]: # (If you experienced crashes, segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)
```

**Comment by un1versal** [comment] 2016-06-07 15:12
Works perfectly well here

**Comment by AndrioCelos** [comment] 2016-06-07 15:16
Is the notify window you're referring to the registered users dialog? If not, where is it?

**Comment by krambock** [comment] 2016-06-07 15:26
If you select the IRC server, then click on Notify Window... it opens the notify list..  I'm attaching a Screen Shot.. 
![screenhunter_281 jun 07 10 24](https://cloud.githubusercontent.com/assets/18543383/15863819/2434d2d0-2c9a-11e6-8545-4976ddaeb3cd.jpg)
I use Kvirc 4.20 as portable and works fine...  I'm using Kvirc 4.9.2 as portable too

**Comment by un1versal** [comment] 2016-06-07 15:28
![capture](https://cloud.githubusercontent.com/assets/3521959/15863790/56229110-2ccc-11e6-872c-ed5916ed765a.PNG)

I dont normally use this but I can confirm it works

I registered Andrio (as a test) via popup, but can be done any way you like all work. Then opened the registered user list select input line and press **ctrl+shift+u** select andrio from the list of registered users, edit his nick, a new dialog opens > Properties tab and tick box

**Comment by krambock** [comment] 2016-06-07 15:37
And how do you get notified if that user is online?   I've just tried it again with myself using a diferent nick...  It is still not showing on the list. 
![screenhunter_02 nov 18 22 16 2](https://cloud.githubusercontent.com/assets/18543383/15864225/daad4488-2c9b-11e6-856c-067851f7c526.jpg)

**Comment by AndrioCelos** [comment] 2016-06-07 15:40
When you move the mouse over their nickname in a user list, does the tooltip say that they are registered?

**Comment by un1versal** [comment] 2016-06-07 15:40
you get notified I think in active window

idk how you populate that notify list you shown on screenshot, but the only list that matters is not that one afaik its the registered users dialog list that matters,

**Comment by krambock** [comment] 2016-06-07 15:48
@AndrioCelos  yes it says it's registered...  
@un1versal  I am attaching the screen on Kvirc 4.2.0 where I get a notification on the console, and yes it should show on the active window, and it's listed on the notify window
So it works on the "stable" version 
![screenhunter_286 jun 07 10 45](https://cloud.githubusercontent.com/assets/18543383/15864531/1e25dbde-2c9d-11e6-8325-ce1a6bfd9605.jpg)

**Comment by un1versal** [comment] 2016-06-07 15:51
But notifications work (they work here), what doesnt work then is this list being populated, right?

Reference: Respective code entries https://github.com/kvirc/KVIrc/search?utf8=%E2%9C%93&q=m_pNotifyListView+&type=Code

**Comment by krambock** [comment] 2016-06-07 15:54
I don't get a notification nor the user is listed.

**Comment by un1versal** [comment] 2016-06-07 15:56
Notifications work here fine, populating Notify list doesnt.

But Im on Linux will have to test that on Windows whenever I boot a windows VM for some other testing.

Andrio what about you?

**Comment by un1versal** [comment] 2016-06-07 16:10
Actually... I managed to get this all to work...

![capture](https://cloud.githubusercontent.com/assets/3521959/15865377/6b973518-2cd2-11e6-9f8f-90a75d5b2329.PNG)

![capture](https://cloud.githubusercontent.com/assets/3521959/15865455/adbcde20-2cd2-11e6-84dc-e2d2351a4327.PNG)

so I go back to saying this works fully

**Comment by AndrioCelos** [comment] 2016-06-07 16:14
It appears that KVIrc tries to clear the `WATCH` list with the command `watch clear`. On my testing server, which is InspIRCd 2.0.20, that doesn't work. The correct command is `watch c`.
A specification of the `WATCH` command is here. https://github.com/grawity/irc-docs/blob/master/client/draft-meglio-irc-watch-00.txt#L297

**Comment by un1versal** [comment] 2016-06-07 16:34
> It appears that KVIrc tries to clear the WATCH list with the command watch clear. On my testing server, which is InspIRCd 2.0.20, that doesn't work. The correct command is watch c.
> A specification of the WATCH command is here. https://github.com/grawity/irc-docs/blob/master/client/draft-meglio-irc-watch-00.txt#L297

Fixed in https://github.com/kvirc/KVIrc/pull/2004

krambock can you confirm your KVIrc global settings in 4.9.2 are done properly at least as mine were, soon as I ticked a couple of boxes the Notify list populated immediately. and as I had previously said and is confirmed working both options in 4.9.2

**Comment by krambock** [comment] 2016-06-07 16:46
@un1versal you are right...  that setting somehow got not selected when i reinstalled the new version.
![screenhunter_287 jun 07 11 44](https://cloud.githubusercontent.com/assets/18543383/15866717/73e2ca66-2ca5-11e6-8c44-9a016187db51.jpg)

**Comment by staticfox** [comment] 2016-06-07 16:48
A commit broke the config system so a good amount of settings won't carry over. You'll want to look over the rest of your settings to make sure they're right, or just start over. Closing.

**Closed as completed by staticfox** 2016-06-07 16:48 UTC
Labels: Status ■ Invalid, Status ■ Works for Me

**Comment by un1versal** [comment] 2016-06-07 16:51
> A commit broke the config system so a good amount of settings won't carry over. You'll want to look over the rest of your settings to make sure they're right, or just start over. Closing.

https://github.com/kvirc/KVIrc/blob/73c0e49f372e7a88720fc67467951ce4d05ed405/src/kvirc/kernel/KviOptions.cpp#L108 

that setting is false by default

**Comment by un1versal** [comment] 2016-06-07 17:02
works for me is easier for me to reference previous issues e.g https://github.com/kvirc/KVIrc/issues?q=label%3A%22Works+for+Me%22+is%3Aclosed

some like this have some info attached.
