### ISSUE TITLE
No self part messages when boolShowOwnParts is false and boolKeepChannelOpenOnPart is true

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2107] opened 2016-08-14 17:24 UTC
@AndrioCelos said he gets these self part messages in active window, but I just tested a Windows build and there's are absolutely none either.
### Expected behavior

That you get notification in active channel when you part another channel on network when **boolShowOwnParts** is false and `boolKeepChannelOpenOnPart` is true
### Actual behavior

no notification whatsoever.

note: when **`boolShowOwnParts`** is true you get notifications in console as expected.
### Steps to reproduce the issue

See

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17649812/28ebc1aa-6235-11e6-8fb6-6cd6a84f81d9.gif)

you can also do `/part #channelname`
## Linux

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-91-generic
System version: #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-14 11:36:26 UTC
Sources date: 20160813
Revision number: git-6928-g921bcb6
System name: Linux-3.13.0-91-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```
## Windows

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 26 Stepping 5
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-08-14 14:23:19 UTC
Sources date: 20160814
Revision number: git-6929-gbda37ab
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by wodim** [comment] 2016-08-14 17:59
Unless I'm not understanding this correctly, this is working as intended.

**Comment by wodim** [comment] 2016-08-14 18:00
- **boolShowOwnParts is true**: part message is printed in the console, then the channel window is closed
- **boolShowOwnParts is false**: part message is printed in the channel window, then the channel window is closed

**Comment by IceN9ne** [comment] 2016-08-14 21:55
You would need `boolKeepChannelOpenOnPart = true` for `boolShowOwnParts = false` to be visible.  I always disagree with dumping things to the active channel as it never makes sense to have things unrelated to the active channel shown only in the active channel.  Try finding it later if you need to see the message again.

**Comment by staticfox** [comment] 2016-08-14 22:01
Where does it say anything about active channel?

**Comment by IceN9ne** [comment] 2016-08-14 22:03
@staticfox 

In the Expected Behavior section of un1versal's issue.

**Comment by staticfox** [comment] 2016-08-14 22:05
That's not expected behavior at all, this is working as it should. If anything this should be a feature request or a behavior change request. Classifying it as a bug seems wrong.

**Comment by wodim** [comment] 2016-08-14 22:08
Take into account that if **boolKeepChannelOpenOnPart** is on and **boolShowOwnParts** is off, the part message stays in the channel window as it should.

I don't understand the rationale behind printing the part message in the window that regains focus after the current window is closed. In most cases, it will be a random window. In all cases, it's going to be an unrelated window.

**Comment by staticfox** [comment] 2016-08-14 22:13
The only way it would ever make sense is if a rogue oper uses `SVSPART`, but even then, that's an extreme edge case much like this whole issue. IMO this can easily be solved with scripting if you desire, and as there is no rationale behind this as wodim pointed out, I'm going to close this issue.

**Comment by un1versal** [comment] 2016-08-14 23:19
> boolShowOwnParts is true: part message is printed in the console, then the channel window is closed

Correct

> boolShowOwnParts is false: part message is printed in the channel window, then the channel window is closed

INCORRECT, nothing gets printed anywhere, I have even left channel window open on parts nothing gets printed to the window being closed or to ANY window whatsoever.

> That's not expected behavior at all, this is working as it should. If anything this should be a feature request or a behavior change request. Classifying it as a bug seems wrong.

and so we close it... I will now see any report classed as a bug that I dont think its a bug and close it.

it would be nicer if the messages arent printed to console get printed to active window, unless of course this would violate some sacred rule of IRC standards.

> @staticfox
> 
> In the Expected Behavior section of un1versal's issue.

Its would be nice if you read what I actually say at beginning of report. see

> @AndrioCelos said he gets these self part messages in active window, but I just tested a Windows build and there's are absolutely none either.

so I already had some feedback from someone claiming this works, when I cant get it to show anything whatsoever,

If that is wrong idk, I cant get any messages whatsoever.

**Comment by wodim** [comment] 2016-08-14 23:24
tru, it's a bug

> Take into account that if boolKeepChannelOpenOnPart is on and boolShowOwnParts is off, the part message stays in the channel window as it should.

That is not working now.

**Comment by IceN9ne** [comment] 2016-08-15 00:11
Currently implemented logic:

`boolKeepChannelOpenOnPart=true && boolShowOwnParts=true`: Part message is shown in dead channel window.
`boolKeepChannelOpenOnPart=true && boolShowOwnParts=false`: Part message isn't shown at all.
`boolKeepChannelOpenOnPart=false && boolShowOwnParts=true`: Part message is shown in console.
`boolKeepChannelOpenOnPart=false && boolShowOwnParts=false`: Part message isn't shown at all.

What is the desired logic?  I'll patch what is wanted.

Description of boolShowOwnParts from the Options Widget: "Show own parts in the console"

**Comment by un1versal** [comment] 2016-08-15 00:22
> boolKeepChannelOpenOnPart=true && boolShowOwnParts=true: Part message is shown in dead channel window.

mmm so its broken? boolShowOwnParts=true means print to console or no? Im not sure whats desired but as is seems odd.

edit
When both bools are true : show message both in dead channel and console. (to keep it simple and logical.)

> boolKeepChannelOpenOnPart=true && boolShowOwnParts=false: Part message isn't shown at all.

I think this is clear what should happen part msg should be printed to dead channel then

> boolKeepChannelOpenOnPart=false && boolShowOwnParts=true: Part message is shown in console.

That is whats expected from this.

> boolKeepChannelOpenOnPart=false && boolShowOwnParts=false: Part message isn't shown at all.

Well that seems fair since no message is expected, but since things should be clearer here.
since  boolKeepChannelOpenOnPart and boolShowOwnParts seem to be tied together but they are in separate UI parts albeit they are in correct places theres no indication these may even work together.

Im not exactly sure on the first one. But lets see if better ideas come out.

**Comment by IceN9ne** [comment] 2016-08-15 00:33
Depends on the definition of `boolShowOwnParts` is.  In the options widget, it says "Show own parts in the console", but in the logical implementation of it, it's "Show own parts".

For reference, the only parts in the code that use this:

https://github.com/kvirc/KVIrc/blob/master/src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp#L457-L480

**Comment by un1versal** [comment] 2016-08-15 00:55
> **Depends on the definition of**...
> ...but in the logical implementation of it, it's "Show own parts""

and the result is wonderful and fully logical,`</sarcasm>` on one hand options labels should be labeled clearly according to logic and action performed. (in this case only one of those criteria is filled) on the other big wtf moments...

`<rant>`slightly related: bool/uint/optionsname should also be named in short but clear manner to satisfy those criteria...

however its obvious when trying to correct some things and specially renaming boll/uints that your told it breaks scripts so most times things are ignored (and only pile up and become more argh inducing) and left behind/forgotten and labels are changed/corrected.

terrible practice, as it fosters confusion, but thats OK as long as scripts work... :tongue: pfff`</ramt>`

**Comment by AndrioCelos** [comment] 2016-08-15 06:54
My own part messages are normally displayed in the window of the channel in question. If there's no such window, they go to the console. I'd prefer it that way.

**Comment by un1versal** [comment] 2016-08-15 07:11
> My own part messages are normally displayed in the window of the channel in question

So you have `boolKeepChannelOpenOnPart=true && boolShowOwnParts=true`?

**Comment by AndrioCelos** [comment] 2016-08-15 07:12
Yes.

**Comment by un1versal** [comment] 2016-08-15 07:14
> If there's no such window, they go to the console. I'd prefer it that way.

well, you cant just say that(you can but what does that cover?), theres several possible combinations between the 2 bools and some are broken see https://github.com/kvirc/KVIrc/issues/2107#issuecomment-239708128

my suggestions are on post after that.

**Comment by un1versal** [comment] 2016-08-15 07:28
OK revised reply for @IceN9ne earlier question.
- boolKeepChannelOpenOnPart=**true** && boolShowOwnParts=**true** **(show messages in both dead-win and console)**
- boolKeepChannelOpenOnPart=**true** && boolShowOwnParts=**false** **(show message in dead-win)**

these stay as they are
- boolKeepChannelOpenOnPart=**false** && boolShowOwnParts=**true** (show msg in console)
- boolKeepChannelOpenOnPart=**false** && boolShowOwnParts=**false** (dont show any msgs)

.... thats more or less logical unless someone else has better idea.

**Closed as completed** 2016-08-16 16:41 UTC
Labels: Type ■ Bug, Status ■ Currently Being Worked On
