### ISSUE TITLE
Using backspace after entering long input doesn't scroll text back

### ISSUE THREAD

**Issue by TheCycoONE** [kvirc/KVIrc#1868] opened 2016-02-05 17:35 UTC
In most text boxes (including native Qt text boxes) if you type text so long as to scroll the visible region then hitting backspace leaves the cursor at the end of the text box but scrolls the visible region back. In KVirc after typing a very long line in the input box, if you press backspace the cursor moves back and there is no text after the cursor but the beginning of the line is still cut off. This makes it more difficult to determine the appropriate place to backspace to if you are trying to go back further than what is in the visible space.

```
KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Professional (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 42 Stepping 7
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-02-05 03:12:34 UTC
Sources date: 20160102
Revision number: git-6215-gd1d891a
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
```

**Comment by TheCycoONE** [comment] 2016-02-05 17:37
![kvirc](https://cloud.githubusercontent.com/assets/823433/12854001/3c159196-cc05-11e5-8744-9ee3d2c22197.png)

Showing the text input, after erasing what follows 'because'

**Comment by un1versal** [comment] 2016-02-05 17:39
Sorry I dont understand whats suppose to happen,

**Comment by TheCycoONE** [comment] 2016-02-05 17:44
The text input should show what is before: `t that the beginning` to fill up the remainder of the box, until it gets back to the beginning, then the cursor should move. Try it in another application with a text box.

**Comment by TheCycoONE** [comment] 2016-02-05 17:46
Actually no need to look to another application. Try it in the Server: text box on Servers and Configuration.

**Comment by un1versal** [comment] 2016-02-05 18:33
meh... I dont see any difference in behavior.

**Edit** OK I see it you fill the line and delete a few characters and on input bar the characters at the left side visible end are static while on other input lines for each characters you delete on the right another becomes visible on left hand side.

**Comment by DarthGandalf** [comment] 2016-02-05 18:48
I see the difference. Type very long string, then press backspace.
Behavior 1: text doesn't move, cursor moves left ← our input editor
Behavior 2: text moves right, cursor doesn't move ← usual text fields

2016-02-05 18:33 GMT+00:00 un1versal notifications@github.com:

**Comment by un1versal** [comment] 2016-02-05 21:36
This feels more like a feature request.

Consistency wise it would be nice to have all things behave in similar manner, but the difference in behavior observed isnt causing any bug (bugs) I can see. (even if its sort of that way)

KVIrc is the epitome of higgledy-piggledy  and this is yet another drop in the bucket of things that should be but aren't. With some luck KVIrc will get there. SO heres my unabashed +1

**Comment by TheCycoONE** [comment] 2016-02-05 21:49
I reported it because in the past it has caused me issues, inadvertently sending the start of one sentence with the end of another because I thought I had erased further than I had.

That said I trust your judgement.

**Comment by un1versal** [comment] 2016-02-05 21:52
I had that issue before see https://github.com/kvirc/KVIrc/issues/1823 and that was fixed.

Heck OK, we have so many issues one more isn't gonna hurt. bug marked we can downgrade if it cant be duplicated....

At this rate 5.x will be out in 10 years. lol

**Comment by un1versal** [comment] 2016-02-06 23:36
@TheCycoONE Actually ill agree, running a few more tests, indeed this issue is an extension of #1823 

At least the issue is now confined to only one way to duplicate which is this one.

**Comment by wodim** [comment] 2016-02-06 23:46
It's the same. The wonders of our custom input field...

**Comment by un1versal** [comment] 2016-02-06 23:49
I wonder how many bugs will be introduced by fixing this one :D

**Comment by wodim** [comment] 2016-02-06 23:53
Many, I guess. For example you can use Ctrl+Backspace to remove the previous word but you can't use Ctrl+Delete to remove the next word. There are dozens of those bugs and it's a game of whack-a-mole.

**Comment by un1versal** [comment] 2016-02-06 23:59
... and noone doing the whacking unless stalked on IRC. :D :/ sadly.

**Comment by wodim** [comment] 2016-02-07 13:30
Once again I was thinking of changing KviInputEditor for a QLineEdit, it's something to think about. Although it would require a big ass rewrite of important parts of the client.

**Comment by VFiber** [comment] 2016-02-24 09:24
Just looked into KviInputEditor, and even changing to QLineEdit would require a major "pimp" to add every feature that KviInputEditor has. However KVIInputEditor needs (I know at least 3 confirmed) bug cleanup and maybe some refactor.

**Comment by un1versal** [comment] 2016-02-24 10:20
And no one is brave enough to tackle these issues :D which are imo basic functionality which are release blockers.

**Comment by un1versal** [comment] 2016-04-23 09:30
removed feature request this is just a bug form the way 99.999% of any input fields work

**Comment by un1versal** [comment] 2016-07-07 08:50
still going strong

**Closed as completed** 2016-11-30 08:36 UTC
Labels: Component ■ GUI, Type ■ Bug, Status ■ Confirmed, Version ■ 5.0.0 Aria
