### ISSUE TITLE
Broken keys- Numpad Enter behaves like spacebar - Workaround posted

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#1655] opened 2015-10-05 06:05 UTC
Hi,

I would like to report that with revision: git-5475-g9a195de, Enter key on the numeric pad acts like spacebar, and Ctrl+W prints a literal W.

**Comment by ctrlaltca** [comment] 2015-10-05 06:38
Can i ask your OS and Qt version please?

**Comment by kartagis** [comment] 2015-10-05 06:39
Ubuntu 14.04 and Qt4

**Comment by ctrlaltca** [comment] 2015-10-05 06:48
I suppose you mean ubuntu 14.10. It's known that ubuntu can have problems with qt applications shortcuts, due to the way they try to integrate them. The relevant bug should be: https://bugs.launchpad.net/appmenu-qt5/+bug/1380702
Afaik there are some known workarounds, but your mileage may vary.

**Comment by kartagis** [comment] 2015-10-05 06:49
Should I upgrade to Qt5? And I mean Ubuntu 14.04

**Comment by kartagis** [comment] 2015-10-05 06:50
`lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty`

**Comment by ctrlaltca** [comment] 2015-10-05 07:01
Hum.. 14.04 shouldn't be affected by that bug; sorry.
Anyway,building with qt5 could be a good try; i suggest you not to use ubuntu's own version, but to attempt using a more recent qt version like this one: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt541

**Comment by kartagis** [comment] 2015-10-05 07:03
W: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt541/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ctrlaltca** [comment] 2015-10-05 07:12
Sorry, i linked a ppa for "precise" instead of the correct one for "trusty".
Please have a look at https://launchpad.net/~beineri for the correct ppa

**Comment by un1versal** [comment] 2015-10-05 08:25
This is Qt independent and its been happening for while, its not specific to the KVIrc version mentioned on report.

I compile, use Qt5 (5.2.1) and tested with Qt4 also, Ubuntu 14.04LTS and I can confirm this bug.
Any version in master for last few weeks no idea when this started happening.

**Comment by kartagis** [comment] 2015-10-05 10:10
So, what's the next step? Just wait?

**Comment by wodim** [comment] 2015-10-05 10:23
I'd wait until Ubuntu fixes it, honestly.

**Comment by un1versal** [comment] 2015-10-05 10:26
@kartagis If this is Ubuntu Bug should be reported to Ubuntu, Else you can wait forever here with this report.
Are you going to report it to them or find out f they have already such report? If it exists or you make a report, please link it here in your reply. Thanks.

Ill trust what wodim and ctrlaltca say and mark this as 3rd party.

**Comment by un1versal** [comment] 2015-10-06 08:07
I was investigating this because it bugs me also...

With xev command you are able to see a crucial difference between normal enter key and numbpad enter

**Numbpad Enter**

```
KeyRelease event, serial 37, synthetic NO, window 0x3800001,
    root 0x17b, subw 0x3800002, time 12012706, (38,47), root:(640,487),
    state 0x10, keycode 104 (keysym 0xff8d, KP_Enter), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

**Normal Enter**

```
KeyRelease event, serial 37, synthetic NO, window 0x3800001,
    root 0x17b, subw 0x3800002, time 12008930, (38,47), root:(640,487),
    state 0x10, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

So I think its a question (for a workaround) to remap **`(keysym 0xff8d, KP_Enter)`** to **`(keysym 0xff0d, Return)`***

No idea how to fix that (properly) in Ubuntu and friends though

**Comment by kartagis** [comment] 2015-10-06 08:11
Remap on Ubuntu? Will that not break existing functionality?

On 6 October 2015 at 11:07, un1versal notifications@github.com wrote:

> I was investigating this because it bugs me also...
> 
> With xev command you are able to see a crucial difference between normal
> enter key and numbpad enter
> 
> _Numbpad Enter_
> 
> KeyRelease event, serial 37, synthetic NO, window 0x3800001,
>     root 0x17b, subw 0x3800002, time 12012706, (38,47), root:(640,487),
>     state 0x10, keycode 104 (keysym 0xff8d, KP_Enter), same_screen YES,
> "   XLookupString gives 1 bytes: (0d) "
>     XFilterEvent returns: False
> 
> _Normal Enter_
> 
> KeyRelease event, serial 37, synthetic NO, window 0x3800001,
>     root 0x17b, subw 0x3800002, time 12008930, (38,47), root:(640,487),
>     state 0x10, keycode 36 (keysym 0xff0d, Return), same_screen YES,
> "   XLookupString gives 1 bytes: (0d) "
>     XFilterEvent returns: False
> 
> So I think its a question (for a qorkaround) to remap _(keysym 0xff8d,
> KP_Enter)_ to _(keysym 0xff0d, Return)_*
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kvirc/KVIrc/issues/1655#issuecomment-145776748.

## 

This is an HTML

**Comment by un1versal** [comment] 2015-10-06 08:48
I ran this commad

`xmodmap -e "keycode 104 = Return"`

and now my Numbpad Enter Key under xev reports

```
KeyRelease event, serial 37, synthetic NO, window 0x3800001,
    root 0x17b, subw 0x0, time 15091454, (163,-15), root:(765,425),
    state 0x10, keycode 104 (keysym 0xff0d, Return), same_screen YES,
    XKeysymToKeycode returns keycode: 36
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

And behaves like Enter Key does.

**Comment by un1versal** [comment] 2015-10-07 15:37
You going to have to redo this every time you reboot unless you make change permanent btw.

**Comment by un1versal** [comment] 2015-10-29 11:20
Closing this in favor of  https://github.com/kvirc/KVIrc/wiki/FAQ#why-does-numpad-enter-behave-like-spacebar-in-linux

**Closed as completed by un1versal** 2015-10-29 11:20 UTC
Labels: Status ■ Confirmed, Component ■ 3rd Party, Status ■ Workaround Posted
