### ISSUE TITLE
Select Server to nick registration

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#933] opened 2015-07-26 02:55 UTC
**Reported by Fa|ko on 01 Sep 2010 00:37:22 UTC**
In Tab "register user" would be convenient to select the parent server of registration, especially if you use the notify list for two different server, because users could use the same nickname in different network and then wrongly reported

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/933

**Comment by un1versal** [comment] 2016-06-09 11:12
This is pretty much a duplicate of https://github.com/kvirc/KVIrc/issues/275 closing and merging this ticket details there.

**Closed as completed** 2016-06-09 11:12 UTC
Labels: Status  ■ Duplicate
