### ISSUE TITLE
Dehighlight line when closing search bar

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1431] opened 2015-07-26 03:50 UTC
**Reported by Visitor_099 on 12 Nov 2013 02:53:24 UTC**
When doing a search in a chat window, there is a highlight on the whole line where the result is found. However, that highlight doesn't disappear when the search bar is closed and moves to whatever line is clicked in the window. There is no way to make it go away.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1431

**Comment by pragmaware** [comment] 2015-08-23 03:09
Can't reproduce it with the latest git. Probably fixed by some previous commit.

**Closed as completed by pragmaware** 2015-08-23 03:09 UTC
Labels: Component ■ Core, Type ■ Bug, Version ■ 4.3.2 Aria
