### ISSUE TITLE
"split view" notices pane takes actions instead of chat pane. e.g. scroll, font-size (^+, ^-), and search

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1319] opened 2015-07-26 03:40 UTC
**Reported by smashingx on 31 Aug 2012 19:11:09 UTC**
I was wondering why always when I press the key up page or down page the one that goes or up is the window where all the join/lefts are logged the one that moves and not the channel (I have the split view)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1319

**Comment by DarthGandalf** [comment] 2015-07-26 03:40
**Modified by jaggz on 29 May 2013 20:45:43**
Summary: wrong window has the focus when trying to move it up or down. → "split view" notices pane takes actions instead of chat pane. e.g. scroll, font-size (^+, ^-), and search

**Comment by un1versal** [comment] 2015-12-30 06:02
Can dup and confirmed with current dev, sound like yet another focus type issue since even by selecting the specific bottom window you can only control the join/parts with pgup/down keys as decribed by op.

**Comment by un1versal** [comment] 2016-06-11 07:48
There is another bug with split view.

reset zoom also only works on the top pane.

So: zoom in via **Ctrl++** zoom out via **Ctrl+-** and reset zoom **Ctrl+0** and **Ctrl+F** control only affect the top pane as reported.

**Comment by IceN9ne** [comment] 2016-09-04 04:07
What is the desired behavior?  We want all key combos to affect the bottom split instead of the top split?  Or do we want some kind of focus ability where if we click in the top split, all key combos go to the top split, and if we click in the bottom split, all key combos go to the bottom split?

I'm kind of in favor of the second choice, but the first choice is a much simpler fix.

**Comment by un1versal** [comment] 2016-09-04 07:14
The first choice is not much better imo. :-1: 

The second choice :+1: is the only sane alternative, so I also vote for that, that way at least you have a way to also decide which pane to reset. 

~~Maybe in fixing this issue in that way, a few other focus related bugs will also be fixed by magic.~~

edit wishful thinking but no other focus related bugs were fixed.

thanks ;)

**Closed as completed** 2016-09-05 11:37 UTC
Labels: Component ■ Core, Component ■ GUI, Type ■ Bug, Status ■ Confirmed, Version ■ 5.0.0 Aria
