### ISSUE TITLE
KVIrc instantly crashes and can't startup on Wayland session

### ISSUE THREAD

**Issue by MirceaKitsune** [kvirc/KVIrc#2523] opened 2022-05-20 20:41 UTC
I recently noticed that KVirc will no longer start up when using a Wayland session. It works perfectly fine in X11 but if I choose Wayland it refuses to run. No detail is provided if starting up from a console, just the typical "segmentation fault" which is a fancier keyword for "it crashed". As I don't run from Git and using gdb is complex I hope others can easily reproduce this.

My OS is Manjaro and my DE is KDE, this issue happens with the Wayland session for Plasma. KVIrc is installed from the distro's system packages. Note that to test Wayland on KDE you need to install the package plasma-wayland-session in Manjaro. I haven't tried reproducing it in a VM but hopefully it works there too which should make testing easy. This is the system info from the about section, X11 session which I'm still using by default until Wayland is more stable.

```
KVIrc 5.0.0 'Aria'

Runtime Info:
System name: Linux 5.17.6-1-MANJARO
System version: #1 SMP PREEMPT Mon May 9 07:52:43 UTC 2022
Architecture: x86_64
Qt version: 5.15.3
Qt theme: breeze

Build Info:
Build date: 2021-12-03 00:27:39 UTC
Sources date: 20160102
Revision number: 
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt
Qt version: 5.15.2
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, OSS, Transparency, DCCVoice, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.1.1o 3 May 2022
OpenSSL compiler flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -Wa,--noexecstack -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OpenSSL built on: Tue May 3 17:34:24 2022 UTC
```

**Comment by MirceaKitsune** [comment] 2022-07-18 21:34
I'm still getting the crash on Plasma 5.25.3 on Manjaro. Is there any news on this please? If the issue can't be addressed I'll likely have to switch to a new IRC client once everything else allows moving to Wayland.

**Comment by ctrlaltca** [comment] 2022-07-19 07:11
> As I don't run from Git and using gdb is complex I hope others can easily reproduce this.

https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace

> Is there any news on this please?

No one stepped up because nobody could reproduce your problem. I'm afraid news on your issue can only come from you atm.

**Comment by MirceaKitsune** [comment] 2022-10-20 14:48
Sorry for the delay. I set up a VM to test the issue: It appears the latest Git version doesn't produce this crash, KVIrc will start fine on Plasma Wayland session. Either it's related to how the package is compiled, or most likely it was fixed in a later commit.

Does anyone know when a new KVIrc release may take place? Would it be possible to update the Manjaro package? I'll ask on the Manjaro forum as well to see about this, but possibly let me know who manages the repos and if they can help.

**Comment by sclintow** [comment] 2023-03-25 22:15
The kvirc 5.0.0 version shipped with Fedora 37 has an instant crash when running under Wayland.  I will try building the latest Git version to see if it runs.    

[root@pulsar download]# rpm -qi kvirc
Name        : kvirc
Version     : 5.0.0
Release     : 18.fc37
Architecture: x86_64
Install Date: Sat 25 Mar 2023 03:24:04 PM MDT
Group       : Unspecified
Size        : 37250327
License     : GPLv2+ with exceptions
Signature   : RSA/SHA256, Sun 24 Jul 2022 05:41:24 PM MDT, Key ID f55ad3fb5323552a
Source RPM  : kvirc-5.0.0-18.fc37.src.rpm
Build Date  : Thu 21 Jul 2022 11:12:25 AM MDT
Build Host  : buildvm-x86-30.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://kvirc.net/
Bug URL     : https://bugz.fedoraproject.org/kvirc
Summary     : Free portable IRC client

**Comment by ninmba** [comment] 2023-03-27 03:06
I wonder if there's output when you run kvirc in terminal

**Comment by KottV** [comment] 2023-09-27 06:23
I've build KVirc from current mster https://github.com/kvirc/KVIrc/commit/681f0940b6499d83b35bbfea2695aaedb34726e2
And no crashes under wayland.

**Comment by ctrlaltca** [comment] 2023-10-18 14:29
Issue fixed, closing

**Closed as completed by ctrlaltca** 2023-10-18 14:29 UTC
